lang: pl
languages: ["pl"]
title:             
email:            
description:       
author:
encoding: UTF-8

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-coffeescript

exclude:
  - LICENSE
  - README.md
  - fresh.gif
  
# Social Profiles
twitter_username:
github_username:
facebook_username:
